export const GETSTORETRADINGS = 'GETSTORETRADINGS'

export const GETSTORETRADINGSCATEGORY = 'GETSTORETRADINGSCATEGORY'

export const GETSTOREINFO = 'GETSTOREINFO'

export const WEIXINLOADUSERINFO ='WEIXINLOADUSERINFO'

export const ADDSHOPCAR = 'ADDSHOPCAR'

export const REDUCESHOPCAR = 'REDUCESHOPCAR'